name: Deployment
on:
  push:
    branches:
      - 'test'
    paths-ignore:
      - src/test/setup.js
      
jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code to runner
      uses: actions/checkout@v3 
    - name: Install nodejs
      uses: actions/setup-node@v3
    - name: Install dependencies
      run:  npm ci
    - name: Linting
      run: npm run lint

 test:
   runs-on: ubuntu-latest
   needs: lint
   steps:
    - name: checkout code to runner
      uses: actions/checkout@v3 
    - name: Install nodejs
      uses: actions/setup-node@v3
    - name: Install dependencies
      run:  npm ci
    - name: Test
      run: npm test

 build:
   runs-on: ubuntu-latest
   needs: test
   steps:
    - name: checkout code to runner
      uses: actions/checkout@v3 
    - name: Install nodejs
      uses: actions/setup-node@v3
    - name: Install dependencies
      run:  npm ci
    - name: Test
      run: npm run build
    - name: ls on dist
      run: |
        cd dist
        ls

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: |
          dist

 deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: checkout code to runner
      uses: actions/checkout@v3 
    - name: Install nodejs
      uses: actions/setup-node@v3
    - name: Install dependencies
      run:  npm ci
    - name: Test
      run: npm run build
    - name: upload artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files
    - name: ls on dist
      run: |
        cd dist
        ls
       
      
        
      
    
